Update epg-grab.yml

diff --git a/.github/workflows/epg-grab.yml b/.github/workflows/epg-grab.yml
--- a/.github/workflows/epg-grab.yml
+++ b/.github/workflows/epg-grab.yml
@@ -30,12 +30,13 @@ jobs:
           export TZ="Asia/Kuala_Lumpur"
           npm run grab -- --site=mewatch.sg --days=2 --output=../mewatch.xml
           npm run grab -- --site=rtmklik.rtm.gov.my --days=2 --output=../rtmklik.xml
-          npm run grab -- --site=rctiplus.com --days=2 --output=../rctiplus.xml
           npm run grab -- --site=vidio.com --days=2 --output=../vidio.xml
+          npm run grab -- --site=sooka.my --days=2 --output=../sooka.xml
 
       - name: Download Sport EPGs (epg.pw)
         run: |
-          # Muat turun setiap saluran sport secara berasingan
+          # Muat turun setiap saluran secara berasingan
+          curl -L "https://epg.pw/api/epg.xml?channel_id=411967" -o bioskopindo.xml
           curl -L "https://epg.pw/api/epg.xml?channel_id=171939" -o soccer.xml
           curl -L "https://epg.pw/api/epg.xml?channel_id=171988" -o sportstar1.xml
           curl -L "https://epg.pw/api/epg.xml?channel_id=171965" -o sportstar2.xml
@@ -51,8 +52,8 @@ jobs:
           
           git add *.xml
           
-          # Bersihkan fail indihome lama dan fail lain yang tidak digunakan
-          git rm indihome.xml external_epg.xml myepg.xml cignal.xml starhub.xml --ignore-unmatch
+          # Bersihkan fail lama (rctiplus dibuang, sooka ditambah ke repo)
+          git rm rctiplus.xml indihome.xml external_epg.xml myepg.xml cignal.xml starhub.xml --ignore-unmatch
           
-          git commit -m "Update EPG: Added RCTI+ & Vidio, Removed Indihome ($(date))" || echo "Tiada perubahan"
+          git commit -m "Update EPG: Added Sooka, Removed RCTI+ ($(date))" || echo "Tiada perubahan"
           git push
